"""username changed to full_name

Revision ID: bf02b0aafc3d
Revises: 147f4e5289f9
Create Date: 2025-09-29 22:37:24.604724

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql
from sqlmodel import sql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bf02b0aafc3d"
down_revision: Union[str, Sequence[str], None] = "147f4e5289f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_column("users", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.drop_column("users", "full_name")
    # ### end Alembic commands ###
